server:
  port: 8081



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-44310076.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oafz4ah5o0jnstD05d7
            clientSecret: imES3jHHG3CQUng4AjEKbr5U4_tVL8rAmR7nXaKeeYPAN2copAfuqw6w1qfM5crZ
        provider:
          okta:
            issuerUri: https://dev-44310076.okta.com/oauth2/default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        timeoutDuration: 0s
        limitRefreshPeriod: 4s
        limitForPeriod: 2

okta:
  oauth2:
    issuer: https://dev-44310076.okta.com/oauth2/default
    audience: api://default