server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/microservices?authSource=admin
      username: root
      password: root
  application:
    name: RATING-SERVICE

  config:
    import: configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://dev-44310076.okta.com/oauth2/default
    audience: api://default